spring:
  profiles:
    active: dev
  
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password: 
    
  h2:
    console:
      enabled: true
      path: /h2-console
      
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
        format_sql: true
        
  flyway:
    enabled: false  # Deshabilitar Flyway temporalmente para usar H2

# Configuración del adapter externo
sqlserver-adapter:
  enabled: true
  base-url: http://localhost:8080

# Configuración del servicio regulatorio
regulatory:
  report-generation:
    enabled: true
    output-path: ./reports
    temp-path: ./temp

logging:
  level:
    com.sudbank.regulatory: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE 